server {
    listen 80;
    root /usr/share/nginx/html;

    location = /health_check {
        access_log off;
        return 200 'OK';
    }

    # Matches the existing URL structure
    location /data/media/ {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        expires max;
        add_header Cache-Control "public, no-transform";
        access_log off;

        # This will look for files in /usr/share/nginx/html/data/media/
        try_files $uri =404;
    }
}