# NOTE: there is currently NO system for synchronization of these with the harvesting side. I've just copied this
# class over here and effectively run it, so that things are duplicated with values/IDs. This is clearly cheating...
# but: priorities!
class DefaultSections
  class << self
    attr_accessor :sections
  end

  @sections =
    [
      { name: 'Overview',
        parent: nil },
      { name: 'Brief Summary',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#TaxonBiology',
                 'http://rs.tdwg.org/ontology/voc/SPMInfoItems#Introduction',
                 'http://rs.tdwg.org/pccore/Abstract'],
        parent: 'Overview' },
      { name: 'Comprehensive Description',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#GeneralDescription',
                 'http://rs.tdwg.org/ontology/voc/SPMInfoItems#Description',
                 'http://rs.tdwg.org/ontology/voc/SPMInfoItems#Biology'],
        parent: 'Overview' },
      { name: 'Distribution',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Distribution'],
        parent: 'Overview' },
      { name: 'Physical Description',
        parent: nil },
      { name: 'Morphology',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Morphology'],
        parent: 'Physical Description' },
      { name: 'Size',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Size'],
        parent: 'Physical Description' },
      { name: 'Diagnostic Description',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#DiagnosticDescription'],
        parent: 'Physical Description' },
      { name: 'Type Information',
        values: ['http://www.eol.org/voc/table_of_contents#TypeInformation'],
        parent: 'Physical Description' },
      { name: 'Look Alikes',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#LookAlikes'],
        parent: 'Physical Description' },
      { name: 'Development',
        values: ['http://www.eol.org/voc/table_of_contents#Development'],
        parent: 'Physical Description' },
      { name: 'Identification Resources',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Key',
                 'http://www.eol.org/voc/table_of_contents#IdentificationResources'],
        parent: 'Physical Description' },
      { name: 'Ecology',
        parent: nil },
      { name: 'Habitat',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Habitat'],
        parent: 'Ecology' },
      { name: 'Migration',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Migration'],
        parent: 'Ecology' },
      { name: 'Dispersal',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Dispersal'],
        parent: 'Ecology' },
      { name: 'Trophic Strategy',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#TrophicStrategy'],
        parent: 'Ecology' },
      { name: 'Associations',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Associations'],
        parent: 'Ecology' },
      { name: 'Diseases and Parasites',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Diseases'],
        parent: 'Ecology' },
      { name: 'Population Biology',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#PopulationBiology'],
        parent: 'Ecology' },
      { name: 'General Ecology',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Ecology'],
        parent: 'Ecology' },
      { name: 'Life History and Behavior',
        parent: nil },
      { name: 'Behavior',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Behaviour'],
        parent: 'Life History and Behavior' },
      { name: 'Cyclicity',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Cyclicity'],
        parent: 'Life History and Behavior' },
      { name: 'Life Cycle',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#LifeCycle'],
        parent: 'Life History and Behavior' },
      { name: 'Life Expectancy',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#LifeExpectancy'],
        parent: 'Life History and Behavior' },
      { name: 'Reproduction',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Reproduction'],
        parent: 'Life History and Behavior' },
      { name: 'Growth',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Growth'],
        parent: 'Life History and Behavior' },
      { name: 'Evolution and Systematics',
        parent: nil },
      { name: 'Evolution',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Evolution'],
        parent: 'Evolution and Systematics' },
      { name: 'Fossil History',
        values: ['http://www.eol.org/voc/table_of_contents#FossilHistory'],
        parent: 'Evolution and Systematics' },
      { name: 'Systematics or Phylogenetics',
        values: ['http://www.eol.org/voc/table_of_contents#SystematicsOrPhylogenetics'],
        parent: 'Evolution and Systematics' },
      { name: 'Functional Adaptations',
        values: ['http://www.eol.org/voc/table_of_contents#FunctionalAdaptations'],
        parent: 'Evolution and Systematics' },
      { name: 'Physiology and Cell Biology',
        parent: nil },
      { name: 'Physiology',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Physiology'],
        parent: 'Physiology and Cell Biology' },
      { name: 'Cell Biology',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Cytology'],
        parent: 'Physiology and Cell Biology' },
      { name: 'Molecular Biology and Genetics',
        parent: nil },
      { name: 'Genetics',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Genetics'],
        parent: 'Molecular Biology and Genetics' },
      { name: 'Nucleotide Sequences',
        values: ['http://www.eol.org/voc/table_of_contents#NucleotideSequences'],
        parent: 'Molecular Biology and Genetics' },
      { name: 'Barcode',
        values: ['http://www.eol.org/voc/table_of_contents#Barcode'],
        parent: 'Molecular Biology and Genetics' },
      { name: 'Genome',
        values: ['http://www.eol.org/voc/table_of_contents#Genome'],
        parent: 'Molecular Biology and Genetics' },
      { name: 'Molecular Biology',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#MolecularBiology'],
        parent: 'Molecular Biology and Genetics' },
      { name: 'Conservation',
        parent: nil },
      { name: 'Conservation Status',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#ConservationStatus',
                 'http://rs.tdwg.org/ontology/voc/SPMInfoItems#Conservation'],
        parent: 'Conservation' },
      { name: 'Trends',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Trends'],
        parent: 'Conservation' },
      { name: 'Threats',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Procedures',
                 'http://rs.tdwg.org/ontology/voc/SPMInfoItems#Threats'],
        parent: 'Conservation' },
      { name: 'Legislation',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Legislation'],
        parent: 'Conservation' },
      { name: 'Management',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Management'],
        parent: 'Conservation' },
      { name: 'Relevance to Humans and Ecosystems',
        parent: nil },
      { name: 'Benefits',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#Uses',
                 'http://rs.tdwg.org/ontology/voc/SPMInfoItems#Use'],
        parent: 'Relevance to Humans and Ecosystems' },
      { name: 'Risks',
        values: ['http://rs.tdwg.org/ontology/voc/SPMInfoItems#RiskStatement'],
        parent: 'Relevance to Humans and Ecosystems' },
      { name: 'Wikipedia',
        values: ['http://www.eol.org/voc/table_of_contents#Wikipedia'],
        parent: nil },
      { name: 'Notes',
        values: ['http://www.eol.org/voc/table_of_contents#Notes'],
        parent: nil },
      { name: 'Education',
        parent: nil },
      { name: 'Education',
        values: ['http://www.eol.org/voc/table_of_contents#Education'],
        parent: 'Education' },
      { name: 'Education Links',
        parent: 'Education' },
      { name: 'Education Resources',
        values: ['http://www.eol.org/voc/table_of_contents#EducationResources'],
        parent: 'Education' },
      { name: 'High School Lab Series',
        parent: 'Education' },
      { name: 'Citizen Science',
        parent: nil },
      { name: 'Citizen Science links',
        values: ['http://www.eol.org/voc/table_of_contents#CitizenScience'],
        parent: 'Citizen Science' },
      { name: 'References and More Information',
        parent: nil },
      { name: 'Content Partners',
        parent: 'References and More Information' },
      { name: 'Literature References',
        parent: 'References and More Information' },
      { name: 'Bibliographies',
        parent: 'References and More Information' },
      { name: 'Bibliography',
        parent: 'References and More Information' },
      { name: 'Commentary',
        parent: 'References and More Information' },
      { name: 'On the Web',
        parent: 'References and More Information' },
      { name: 'Biodiversity Heritage Library',
        parent: 'References and More Information' },
      { name: 'Comments',
        parent: 'References and More Information' },
      { name: 'Search the Web',
        parent: 'References and More Information' },
      { name: 'Biomedical Terms',
        parent: 'References and More Information' },
      { name: 'Names and Taxonomy',
        parent: nil },
      { name: 'Related Names',
        parent: 'Names and Taxonomy' },
      { name: 'Synonyms',
        parent: 'Names and Taxonomy' },
      { name: 'Common Names',
        parent: 'Names and Taxonomy' },
      { name: 'Taxonomy',
        values: ['http://www.eol.org/voc/table_of_contents#Taxonomy'],
        parent: 'Names and Taxonomy' },
      { name: 'Data',
        parent: nil },
      { name: 'Data Sources',
        parent: 'Data' },
      { name: 'Page Statistics',
        parent: nil },
      { name: 'Content Summary',
        parent: 'Page Statistics' },
      { name: 'IUCN',
        parent: nil },
      { name: 'Database and Repository Coverage',
        parent: nil }
    ]

  def self.create
    @sections.each_with_index do |params, position|
      s = Section.create(name: params[:name])
      if (parent = Section.find_by_name(params[:parent]))
        SectionParent.create(section_id: s.id, parent_id: parent.id)
      end
      # No values on this side. Keep this only to drive home the fact that THIS CLASS WAS COPIED FROM HARVESTING:
      # if params.key?(:values)
      #   params[:values].each do |value|
      #     SectionValue.create(section_id: s.id, value: value)
      #   end
      # end
    end
  end
end
